apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-httpd-service
spec:
  type: {{ .Values.httpd.service.type }}
  ports:
    - port: {{ .Values.httpd.service.port }}
      targetPort: 80
  selector:
    app: httpd
